# -*- coding: utf-8 -*-
"""huma task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKJ0ZADq5GzfZwSMNh0jRQDn1YxW6y9S
"""

def get_user_info():
    # Prompt the user to enter their name, age, email, and favorite number
    name = input("Please enter your name: ")
    age = int(input("Please enter your age: "))
    email = input("Please enter your email: ")
    favorite_number = int(input("Please enter your favorite number: "))

    # Store the inputs in a dictionary with appropriate keys
    user_info = {
        "name": name,
        "age": age,
        "email": email,
        "favorite_number": favorite_number
    }

    # Validate the email format (contains "@" and ".")
    if "@" in email and "." in email:
        print("Email format is valid!")
    else:
        print("Invalid email format. Please try again.")
        return None


    # Print the user's information
    print("\nHere is the information you entered:")
    print(f"Name: {user_info['name']}")
    print(f"Age: {user_info['age']}")
    print(f"Email: {user_info['email']}")
    print(f"Favorite Number: {user_info['favorite_number']}")

def display_user_info(user_info):
    # Display a message using the variables
    message = f"Hello {user_info['name']}, you are {user_info['age']} years old, your email is {user_info['email']}, and your favorite number is {user_info['favorite_number']}."
    print(message)
    return user_info

user_info = get_user_info()
if user_info:
    display_user_info(user_info)

def Is_even(number):
    # Check if the number is even
    if number % 2 == 0:
        print(f"{number} is even.")
        return True
    else:
        print(f"{number} is odd.")
        return False

# Test the function
num = int(input("Enter an integer: "))
Is_even(num)

def convert_temperature(temp, scale):
    # Convert Celsius to Fahrenheit
    if scale.upper() == "C":
        fahrenheit = (temp * 9/5) + 32
        print(f"{temp}°C is equal to {fahrenheit}°F.")
        return fahrenheit
    # Convert Fahrenheit to Celsius
    elif scale.upper() == "F":
        celsius = (temp - 32) * 5/9
        print(f"{temp}°F is equal to {celsius}°C.")
        return celsius
    else:
        print("Invalid scale. Please enter 'C' for Celsius or 'F' for Fahrenheit.")
        return None

# Test the function
temp = float(input("Enter a temperature value: "))
scale = input("Enter the scale (C for Celsius, F for Fahrenheit): ")
converted_temp = convert_temperature(temp, scale)

def find_max_min(numbers_list):
    # Find the maximum and minimum numbers in the list
    max_num = max(numbers_list)
    min_num = min(numbers_list)
    return max_num, min_num

# Prompt the user to enter 5 numbers
numbers = []
for i in range(5):
    num = float(input(f"Enter number {i+1}: "))
    numbers.append(num)

# Find and display the maximum and minimum numbers
max_num, min_num = find_max_min(numbers)
print(f"Maximum number: {max_num}")
print(f"Minimum number: {min_num}")

def update_inventory(inventory_dict, item, quantity):
    # Update the inventory by adding or removing the specified quantity
    if item in inventory_dict:
        new_quantity = inventory_dict[item] + quantity
        # Ensure that the quantity does not go below zero
        if new_quantity < 0:
            new_quantity = 0
        inventory_dict[item] = new_quantity
    else:
        print(f"Item '{item}' not found in inventory.")
    return inventory_dict

# Initialize an inventory dictionary with 5 items
inventory = {
    "Apple": 10,
    "Banana": 20,
    "Carrot": 30,
    "Donut": 40,
    "Egg": 50
}

print("Initial Inventory:")
print(inventory)

# Prompt the user to update the inventory
for i in range(3):
    item = input(f"Enter item {i+1} to update: ")
    quantity = int(input(f"Enter quantity to add/remove ({item}): "))
    inventory = update_inventory(inventory, item, quantity)

print("\nUpdated Inventory:")
print(inventory)

