# -*- coding: utf-8 -*-
"""file handling.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovrLHvr5w-JyGG_lMvjmajn2SZkfPUlm
"""

def read_file(filename):
    try:
        with open(filename, 'r') as file:
            content = file.read()
            print("File contents:")
            print(content)
            words = content.split()
            print(f"Number of words: {len(words)}")
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
    except Exception as e:
        print(f"Error: An error occurred while reading the file: {e}")


def write_file(filename):
    try:
        user_input = input("Enter some text: ")
        with open(filename, 'w') as file:
            file.write(user_input)
        print(f"Text written to '{filename}' successfully.")
    except Exception as e:
        print(f"Error: An error occurred while writing to the file: {e}")


# Read from data.txt
read_file('data.txt')

# Write to output.txt
write_file('output.txt')